# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hiki # ex. I m Chuan
name: Hiki # ex. DONGChuan
email: 414950815@qq.com
myword: 趁年轻，疯狂奔跑吧
location: SHENZHEN,China # ex. Nice, France
# company: MyCompany
# company_url: my_company_website
github_url: https://github.com/Hikiy # ex. https://github.com/DONGChuan
github_username: Hikiy # ex. DONGChuan
description: 记录自己的足迹
favicon: favicon.png # Image must be in assets/images
repository: Hikiy/Hikiy.github.io # ex. DONGChuan/DONGChuan.github.io
logo: pig.svg
# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://Hikiy.github.io
encoding: utf-8
## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jemoji

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 主页

  -
    href: /open-source
    label: 开源项目

  -
    href: /blog
    label: 所有博客

  -
    href:
    label: 编程语言
    subnav:

      -
        subHref: /nodejs
        subLabel: Node.js

      -
        subHref: /java
        subLabel: Java

  -
    href:
    label: 框架
    subnav:

      -
        subHref: /spring
        subLabel: Spring相关

      -
        subHref: /nodeframwork
        subLabel: Node相关

      -
        subHref: /phpframwork
        subLabel: PHP相关
  -
    href:
    label: 操作系统
    subnav:

      -
        subHref: /linux
        subLabel: Linux

  -
    href:
    label: 其它
    subnav:

      -
        subHref: /network
        subLabel: 计算机网络

      -
        subHref: /algorithm
        subLabel: 算法
  # -
  #   href: /bookmark
  #   label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_programming_language: [Java, PHP, Node.js ]
skill_framework: [Spring, String MVC, MyBatis, Spring Boot, egg.js, ThinkPHP]
skill_data: [MySQL, MongoDB, Redis]
skill_web: [HTML, CSS, JS, Ajax]
skill_os: [Windows, Linux]
